version: '3.8'

services:
  auth-db:
    container_name: auth-db
    image: postgres:15
    env_file:
      - ./auth-api/.env
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 5432:5432

  auth-api:
    container_name: auth-api
    build:
      context: ./auth-api
    restart: unless-stopped
    depends_on:
      - auth-db
    command:
      sh -c "./wait-for-it.sh auth-db:5432 --strict --timeout=60 -- python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./auth-api:/code
      - ./wait-for-it.sh:/code/wait-for-it.sh
    working_dir:
      /code
    networks:
      - internal
    ports:
      - 8006:8000
  
  tagging-api:
    container_name: tagging-api
    image: tagging-api
    restart: unless-stopped
    env_file:
      - ./tagging-api/.env
    build: 
      context: ./tagging-api
    volumes:
      - ./wait-for-it.sh:/code/wait-for-it.sh
      - ./tagging-api:/code
    depends_on:
      - tagging-db
    command:
      sh -c "./wait-for-it.sh tagging-db:5432 --strict --timeout=60 -- python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - internal
    ports:
      - 8008:8000

  tagging-db:
    image: postgres:15
    container_name: tagging-db
    restart: unless-stopped
    env_file:
      - ./tagging-api/.env
    volumes:
      - pgdata-tagging:/var/lib/postgresql/data
    networks:
      - internal

  talkeasy-db:
    image: postgres:15
    container_name: talkeasy-db
    restart: unless-stopped
    env_file:
      - ./talkeasy/.env
    volumes:
      - pgdata-talkeasy:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 5436:5432

  talkeasy-api:
    build: ./talkeasy/
    container_name: talkeasy-api
    restart: unless-stopped
    depends_on:
      - talkeasy-db
    command:
      sh -c "./wait-for-it.sh talkeasy-db:5432 --strict --timeout=60 -- python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./wait-for-it.sh:/code/wait-for-it.sh
      - ./talkeasy/:/code
    working_dir:
      /code
    networks:
      - internal

  gateway-api:
    build:
      context: ./api-gateway
    container_name: gateway-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - auth-api
      - talkeasy-api
      - tagging-api
    environment:
      - AUTH_API_URL=http://auth-api:8000
      - TALKEASY_API_URL=http://talkeasy-api:8000
      - TAGGING_API_URL=http://tagging-api:8000
    volumes:
      - ./api-gateway/:/code
    command: 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir:
      /code
    networks:
      - internal

volumes:
  pgdata-tagging:
  pgdata-talkeasy:
  pgdata-auth:

networks:
  internal:
    driver: bridge