version: '3'

services:
  tagger-api:
    container_name: tagger-api
    image: tagger-api
    restart: unless-stopped
    build: 
      context: ./taggerAPI
    ports:
      - "5000:5000"
    volumes:
      - ./taggerAPI/app:/app 
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload